### ISSUE TITLE
Смена языка программирования

### ISSUE THREAD

**Issue by TTimerkhanov** [berendakova/news_portal#1]
Не рассматриваете ли Вы смену языка программирования на что-то более приятное в использовании? Не развертывая Ваше приложение, я уже чувствую, как оно плохо работает. 
Ну и называть файлы транслитом – моветон. 

С наилучшими пожеланиями, Тимур.

**Comment by berendakova** [comment]
Спасибо за комментарий, Тимур! Этот проект -  совместная курсовая работа с командой первокурссников, использование данного языка программирования - обязательное условие, мы все только учимся и совершаем ошибки. 

Успехов Вам, Татьяна.

**Comment by berendakova** [comment]
@TTimerkhanov 
Спасибо за комментарий, Тимур! Этот проект - совместная курсовая работа с командой первокурссников, использование данного языка программирования - обязательное условие, мы все только учимся и совершаем ошибки.

Успехов Вам, Татьяна.
